[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_ENABLE_DEV_TOOLS = "false"

[context.deploy-preview.environment]
  VITE_ENABLE_DEV_TOOLS = "true"

[context.branch-deploy.environment]
  VITE_ENABLE_DEV_TOOLS = "true"